vim.o.termguicolors = true

local palettes = {
  dark = {
    sidebar = "#0D0E10",
    bg = "#111215",
    bg_subtle = "#161718",
    bg_selected = "#1A1B1D",
    border = "#323337",
    border_muted = "#191A1D",
    fg = "#CDD0D7",
    fg_bright = "#EDEDED",
    fg_secondary = "#ABAEB7",
    comment = "#ADADAE",
    muted = "#6F727F",
    dim = "#51545E",
    hint = "#4E4F51",
    red = "#B87D6E",
    orange = "#C18065",
    green = "#A1C592",
    yellow = "#CEB370",
    blue = "#8892B5",
    purple = "#A38FB5",
    cyan = "#8FB3AD",
    coral = "#C99284",
    selection = "#2B2D33",
    terminal = {
      "#1A1B1D", "#B87D6E", "#A1C592", "#CEB370",
      "#8892B5", "#A38FB5", "#8FB3AD", "#CDD0D7",
      "#565758", "#C99284", "#B3D1A4", "#DCC48A",
      "#9FA9C9", "#B8A6C9", "#A4C7C1", "#EDEDED",
    },
  },
  light = {
    sidebar = "#E7E4DE",
    bg = "#F3F1ED",
    bg_subtle = "#ECE9E3",
    bg_selected = "#E1DED7",
    border = "#B8B2A8",
    border_muted = "#D4D0C9",
    fg = "#2E3032",
    fg_bright = "#242424",
    fg_secondary = "#4F5256",
    comment = "#4F5256",
    muted = "#5D6065",
    dim = "#747570",
    hint = "#6C6964",
    red = "#94493F",
    orange = "#8F4E37",
    green = "#456536",
    yellow = "#7B5D16",
    blue = "#526184",
    purple = "#6D587F",
    cyan = "#3F655F",
    coral = "#8E5146",
    selection = "#D7D2C9",
    terminal = {
      "#2E3032", "#94493F", "#456536", "#7B5D16",
      "#526184", "#6D587F", "#3F655F", "#4F5256",
      "#747570", "#A65E50", "#608250", "#927326",
      "#68769A", "#826D93", "#5B817B", "#242424",
    },
  },
}

local p = palettes[vim.o.background == "light" and "light" or "dark"]
local set = vim.api.nvim_set_hl

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "basalt"

local groups = {
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.bg_subtle },
  FloatBorder = { fg = p.border, bg = p.bg_subtle },
  FloatTitle = { fg = p.yellow, bg = p.bg_subtle, bold = true },
  ColorColumn = { bg = p.bg_subtle },
  Cursor = { fg = p.bg, bg = p.fg },
  CursorColumn = { bg = p.bg_subtle },
  CursorLine = { bg = p.bg_subtle },
  CursorLineNr = { fg = p.orange, bg = p.bg_subtle, bold = true },
  LineNr = { fg = p.hint },
  SignColumn = { fg = p.dim, bg = p.bg },
  FoldColumn = { fg = p.dim, bg = p.bg },
  Folded = { fg = p.muted, bg = p.bg_subtle },
  EndOfBuffer = { fg = p.bg },
  NonText = { fg = p.hint },
  Whitespace = { fg = p.border_muted },
  Conceal = { fg = p.muted },
  Directory = { fg = p.blue },
  Title = { fg = p.yellow, bold = true },
  Visual = { bg = p.selection },
  VisualNOS = { bg = p.selection },
  Search = { fg = p.fg_bright, bg = p.bg_selected },
  IncSearch = { fg = p.bg, bg = p.orange },
  CurSearch = { fg = p.bg, bg = p.yellow },
  MatchParen = { fg = p.yellow, bold = true, underline = true },
  Pmenu = { fg = p.fg, bg = p.bg_subtle },
  PmenuSel = { fg = p.fg_bright, bg = p.bg_selected, bold = true },
  PmenuSbar = { bg = p.bg_subtle },
  PmenuThumb = { bg = p.border },
  WildMenu = { fg = p.fg_bright, bg = p.bg_selected },
  StatusLine = { fg = p.fg, bg = p.bg },
  StatusLineNC = { fg = p.dim, bg = p.sidebar },
  TabLine = { fg = p.muted, bg = p.sidebar },
  TabLineFill = { bg = p.sidebar },
  TabLineSel = { fg = p.fg_bright, bg = p.bg_selected, bold = true },
  WinSeparator = { fg = p.border_muted, bg = p.bg },
  VertSplit = { fg = p.border_muted, bg = p.bg },
  MsgArea = { fg = p.fg, bg = p.bg },
  ModeMsg = { fg = p.green, bold = true },
  MoreMsg = { fg = p.green },
  Question = { fg = p.blue },
  WarningMsg = { fg = p.yellow },
  ErrorMsg = { fg = p.red },

  Comment = { fg = p.comment, italic = true },
  Constant = { fg = p.coral },
  String = { fg = p.green },
  Character = { fg = p.green },
  Number = { fg = p.coral },
  Boolean = { fg = p.coral },
  Float = { fg = p.coral },
  Identifier = { fg = p.fg },
  Function = { fg = p.yellow },
  Statement = { fg = p.orange },
  Conditional = { fg = p.orange },
  Repeat = { fg = p.orange },
  Label = { fg = p.orange },
  Operator = { fg = p.fg_secondary },
  Keyword = { fg = p.orange },
  Exception = { fg = p.orange },
  PreProc = { fg = p.purple },
  Include = { fg = p.orange },
  Define = { fg = p.purple },
  Macro = { fg = p.purple },
  PreCondit = { fg = p.purple },
  Type = { fg = p.blue },
  StorageClass = { fg = p.blue },
  Structure = { fg = p.blue },
  Typedef = { fg = p.blue },
  Special = { fg = p.cyan },
  SpecialChar = { fg = p.cyan },
  Tag = { fg = p.orange },
  Delimiter = { fg = p.fg_secondary },
  SpecialComment = { fg = p.muted, italic = true },
  Debug = { fg = p.red },
  Underlined = { fg = p.blue, underline = true },
  Ignore = { fg = p.dim },
  Error = { fg = p.red },
  Todo = { fg = p.bg, bg = p.yellow, bold = true },

  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.yellow },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.cyan },
  DiagnosticOk = { fg = p.green },
  DiagnosticUnderlineError = { undercurl = true, sp = p.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.cyan },

  DiffAdd = { fg = p.green, bg = p.bg_subtle },
  DiffDelete = { fg = p.red, bg = p.bg_subtle },
  DiffChange = { fg = p.blue, bg = p.bg_subtle },
  DiffText = { fg = p.fg_bright, bg = p.selection, bold = true },
  Added = { fg = p.green },
  Changed = { fg = p.blue },
  Removed = { fg = p.red },

  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.blue },
  GitSignsDelete = { fg = p.red },
  TelescopeBorder = { fg = p.border, bg = p.bg },
  TelescopeNormal = { fg = p.fg, bg = p.bg },
  TelescopePromptBorder = { fg = p.border, bg = p.bg_subtle },
  TelescopePromptNormal = { fg = p.fg, bg = p.bg_subtle },
  TelescopePromptPrefix = { fg = p.orange, bg = p.bg_subtle },
  TelescopeSelection = { fg = p.fg_bright, bg = p.bg_selected, bold = true },
  TelescopeMatching = { fg = p.yellow, bold = true },
  WhichKey = { fg = p.orange },
  WhichKeyGroup = { fg = p.blue },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.dim },
  WhichKeyBorder = { fg = p.border },
  TroubleNormal = { fg = p.fg, bg = p.bg },
  TroubleNormalNC = { fg = p.fg, bg = p.bg },
  RenderMarkdownH1Bg = { bg = p.bg_subtle },
  RenderMarkdownH2Bg = { bg = p.bg_subtle },
  RenderMarkdownH3Bg = { bg = p.bg_subtle },
  RenderMarkdownCode = { bg = p.bg_subtle },
  RenderMarkdownCodeInline = { fg = p.yellow, bg = p.bg_subtle },
}

for name, opts in pairs(groups) do
  set(0, name, opts)
end

local links = {
  ["@variable"] = "Identifier",
  ["@variable.builtin"] = "Special",
  ["@variable.parameter"] = "Identifier",
  ["@constant"] = "Constant",
  ["@constant.builtin"] = "Constant",
  ["@module"] = "Type",
  ["@label"] = "Label",
  ["@string"] = "String",
  ["@string.escape"] = "SpecialChar",
  ["@character"] = "Character",
  ["@boolean"] = "Boolean",
  ["@number"] = "Number",
  ["@type"] = "Type",
  ["@type.builtin"] = "Type",
  ["@attribute"] = "PreProc",
  ["@property"] = "Identifier",
  ["@function"] = "Function",
  ["@function.builtin"] = "Special",
  ["@function.call"] = "Function",
  ["@function.method"] = "Function",
  ["@constructor"] = "Type",
  ["@operator"] = "Operator",
  ["@keyword"] = "Keyword",
  ["@keyword.function"] = "Keyword",
  ["@keyword.return"] = "Keyword",
  ["@punctuation"] = "Delimiter",
  ["@comment"] = "Comment",
  ["@comment.todo"] = "Todo",
  ["@markup.heading"] = "Title",
  ["@markup.link"] = "Underlined",
  ["@markup.link.url"] = "Underlined",
  ["@markup.raw"] = "String",
  ["@markup.list"] = "Special",
}

for name, target in pairs(links) do
  set(0, name, { link = target })
end

for index, color in ipairs(p.terminal) do
  vim.g["terminal_color_" .. (index - 1)] = color
end
